### ISSUE TITLE
Expand automated analysis to all launched 18F sites

### ISSUE THREAD

**Issue by nkkl** [18F/a11y-metrics#2]
- [ ] High profile 18F sites
- [ ] All released 18F sites
- [ ] All live (including beta) 18F sites

Non-goal:
- [ ] Alpha or early development 18F sites

**Comment by toolness** [comment]
Um, so this kind of ties into the notion of an "18F dashboard", [one iteration of which](https://github.com/18F/projects) I worked on when I first joined 18F.  I think it got caught up in a lot of stop energy partly because its main champion left 18F, but also because there was a lot of disagreement over what the public-facing goals of such a dashboard were.  I think it might have been decided that more user research needed to be done before we could figure out exactly what an "18F project dashboard" actually *meant* but I'm not sure.

Anyways, I guess all I'm really getting at is the fact that we don't currently have any kind of central "registry" of official 18F projects, whether as a google sheet, an API, or something else.  It's a thorny problem but I can't help but wonder if our project could somehow contribute to solving it. Perhaps just by creating a *convention* that future solutions can reuse. (This could also help take the burden of maintaining an *accurate* registry off the shoulders of the accessibility guild, maybe.)

For example, now that [GitHub added support for "topics"](https://github.com/blog/2309-introducing-topics), we could potentially just add topics to repositories that "tags" them as being high-profile / released / beta / etc, and then our dashboard script (and other non-a11y dashboards) could just find all the projects by crawling GitHub for projects with the appropriate topics.

There is also some kind of file that every project is supposed to have called [`.about.yml`](https://github.com/18F/about_yml#readme), which defines a bunch of 18F-specific metadata about the project. I believe it actually is part of the ATO process, so every official 18F project is *required* to have it, if I'm not mistaken.  That said, part of the reason the dashboard I was working on took a different approach--it stored all project metadata in a relational database instead--was because apparently folks weren't updating their `.about.yml` files because they were too cumbersome to update, so many of them had outdated information.

**Comment by toolness** [comment]
Hmm, I just realized that all launched 18F sites actually are registered with Google Analytics--both 18F's GA account and DAP's. If we use the [GA Reporting API](https://developers.google.com/analytics/devguides/reporting/core/v4/), we could potentially get a list of all major 18F properties, *and* we could get a list of the most visited pages on each one.

The latter could be particularly useful for running `aXe-core` on--for instance, instead of just visiting the homepage of a site (which doesn't give us *that* much information), or instead of crawling the whole site (which could take a really long time, especially on big sites), we could just visit the top 10 most-visited URLs on the site.

**Comment by toolness** [comment]
I was hoping that analytics.usa.gov could help us with this, but it seems that [the analytics.usa.gov API](https://github.com/18F/analytics-reporter/blob/master/reports/usa.json) will only give us the top websites or pages for particular agencies, which wouldn't be as useful.

**Comment by toolness** [comment]
Oh, actually, I think we might be able to get away with just iterating over all 18F repos that match a certain criteria. As of c49f5bb8e480fa5c84ee6da92aa62b12358f304d, this list is:

* api.data.gov - https://api.data.gov
* API-Usability-Testing - https://pages.18f.gov/API-Usability-Testing/
* 18f.gsa.gov - https://18f.gsa.gov
* API-All-the-X - https://pages.18f.gov/API-All-the-X
* C2 - https://cap.18f.gov
* doi-extractives-data - https://useiti.doi.gov/
* discovery - https://discovery.gsa.gov/
* FEC - https://beta.fec.gov
* openFEC - https://api.open.fec.gov/developers
* dashboard - https://18f.gsa.gov/dashboard
* frontend - https://pages.18f.gov/frontend/
* openFEC-web-app - https://beta.fec.gov/data
* calc - https://calc.gsa.gov/
* hub - https://github.com/18F/handbook
* analytics.usa.gov - https://analytics.usa.gov
* before-you-ship - https://pages.18f.gov/before-you-ship/
* cg-site - https://cloud.gov
* accessibility - https://pages.18f.gov/accessibility/
* tock - https://18f.gsa.gov/2015/05/21/TockingTime/
* agile - https://pages.18f.gov/agile/
* api-program - https://pages.18f.gov/api-program/
* pulse - https://pulse.cio.gov
* methods - https://methods.18f.gov/
* pages - https://pages.18f.gov
* joining-18f - https://pages.18f.gov/joining-18f/
* web-design-standards - https://standards.usa.gov
* agile-solicitation-builder - https://github.com/usds/agile-solicitation-builder
* federalist - https://federalist.18f.gov/
* web-design-standards-assets - https://standards.usa.gov
* content-guide - https://pages.18f.gov/content-guide/
* cg-dashboard - https://dashboard.fr.cloud.gov
* open-source-guide - https://pages.18f.gov/open-source-guide/
* fec-style - https://pages.18f.gov/fec-style/
* fec-cms - https://beta.fec.gov
* guides-style - https://rubygems.org/gems/guides_style_18f
* about_yml - https://rubygems.org/gems/about_yml
* atf-eregs - https://atf-eregs.app.cloud.gov/
* dolores-landingham-slack-bot - https://18f.gsa.gov/2015/12/15/how-bot-named-dolores-landingham-transformed-18fs-onboarding/
* brand - https://pages.18f.gov/brand/
* micropurchase - https://micropurchase.18f.gov
* fec-eregs - https://beta.fec.gov/regulations/
* checklistomania - https://checklistomania.app.cloud.gov/
* product-guide - https://pages.18f.gov/product-guide/
* concourse-compliance-testing - https://ci.cloud.gov/pipelines/zap
* identity-idp - https://idp.demo.login.gov/
* vote-gov - https://vote.gov/
* web-design-standards-docs - https://standards.usa.gov
* handbook - https://handbook.18f.gov
* crime-data-explorer - https://crime-data-explorer.fr.cloud.gov/

That's a total of 49 interesting repos. Note that it includes all the sites listed in our current, hand-crafted `websites.json` file.

The definition of "interesting" in this list is a repo that:

* has *either* at least 20 open issues *or* at least 30 stars;
* has been pushed to in the last year or so;
* has a home in the 18F GitHub org (i.e., is not a fork, or located under some other org);
* has a homepage.

By "homepage" we mean the URL that's displayed near the top of the project's GitHub page, e.g.:

> ![homepage](https://cloud.githubusercontent.com/assets/124687/24504775/847be358-1525-11e7-990d-09d358b1fd84.png)

Obviously some of these "homepages" aren't actually where the project is publicly visible--in the case of Tock and Dolores Landingham, for instance, they're links to blog posts about the project.  And in the case of identity-idp, it's a page that's behind authentication.  But we can deal with those separately through heuristics (e.g. "does the project's homepage URL look like a blog post?") or old-fashioned blacklisting.

The big advantage of this algorithmic approach is that we don't have to constantly maintain a list of what all the major 18F projects are. As long as they're in the 18F org, we're good to go.

That said, there might be some 18F projects that are under their own GitHub organization. I think that [eregs](https://github.com/eregs/) is one of these.  If the whole organization represents one giant 18F project, then we can just add this to the list of organizations whose repositories we iterate through, though that *does* mean we have to maintain a list of such organizations.

Also, this approach doesn't obviate the usefulness of leveraging the Google Analytics Reporting API--that would still be really useful for getting information about what sub-pages of each site we want to run `aXe-core` on.

**Comment by nkkl** [comment]
For the short term, let's do something cheap to get everything stood up. Iterating over repos is a perfectly fine near-term solution.

I think there's a lot of value in a specific tag that projects add to their repo — whether it's `about.yml` or a GH topic — because that also gets us a way to identify projects that have an a11y exemption of one kind or another.

For now, let's scope this to projects hosted within 18F's GitHub organization. We can have a future discussion about how we might handle a project in a non-18F organization (I suspect we'd want to have them opt in to our scanning, and incentivize that by providing concrete value to them).

**Comment by toolness** [comment]
Ok, I've implemented the repo-iterating strategy in c34d80a8d288bfa60056fe1ecf73dee3e4f98f14, so I'm going to close this issue... Feel free to open new issues that catch specific projects we've missed, though!
