### ISSUE TITLE
Are aXe passes useful?

### ISSUE THREAD

**Issue by toolness** [18F/a11y-metrics#28]
I'm curious if listing the number of aXe passes for project homepages is actually useful.  I just added it because it seemed like potentially interesting information, but I'm not sure if it actually is.  I'm happy to remove it if folks think it's not useful.

Thoughts @carodew @nickbristow @nkkl ?

**Comment by carodew** [comment]
I think it's good to keep because - 
1. positive reinforcement – it's also good to let people know what they're doing right, not just what they're doing wrong. 
2. I think it's interesting to see the actual number of tests that aXe ran on the page. It does seem to be a crude measure of how complex the page is, which I think is useful to know. 

That being said, if I were asked to name what actions we could take based on those numbers, I'm not sure I could, and that's @nikkl 's criteria for a good metric, so I'm happy to be disagreed with.

**Comment by nickbristow** [comment]
agreed. I think it looks good having the passes.

**Comment by toolness** [comment]
Ok cool! I'll close this issue for now, then, though @nkkl feel free to re-open it if you disagree.
